name: Build Android

on:
  push:
    branches: [main, cicd]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Install dependencies
        run: |
          sudo npm install -g yarn
          yarn
        working-directory: trombone

      - name: Check typescript
        run: yarn tsc
        working-directory: trombone

      - name: Build Android Release
        run: ./gradlew --no-daemon assembleRelease
        working-directory: trombone/android

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: trombone/android/app/build/outputs/apk/release/
