name: Build Android

on:
  push:
    branches: [cicd]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo npm install -g yarn
          yarn
        working-directory: trombone

      - name: Check typescript
        run: yarn tsc
        working-directory: trombone

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install yarn
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g yarn

      - name: Install npm dependencies
        run: yarn
        working-directory: trombone

      - name: Build Android Release
        run: ./gradlew assembleRelease
        working-directory: trombone/android

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: trombone/android/app/build/outputs/apk/release/
