name: Build Android

on:
  push:
    branches: [cicd]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install yarn
        run: |
          sudo apt-get update
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          nvm install --lts --default
          npm install -g yarn

      - name: Install npm dependencies
        run: yarn
        working-directory: trombone

      - name: Check typescript
        run: yarn tsc
        working-directory: trombone

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Install yarn
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          sudo npm install -g yarn

      - name: Install npm dependencies
        run: yarn
        working-directory: trombone

      - name: Build Android Release
        run: ./gradlew assembleRelease
        working-directory: trombone/android

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: trombone/android/app/build/outputs/apk/release/
