name: Check Typescript

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: install android sdk
        run: sudo apt-get update && sudo apt-get install -y android-sdk

      - name: Install dependencies
        run: |
          sudo npm install -g yarn
          yarn
        working-directory: trombone

      - name: Check typescript
        run: yarn tsc
        working-directory: trombone
